apiVersion: apps/v1
kind: Deployment
metadata:
  name: danger-web
spec:
  template:
    spec:
      containers:
      - name: php-fpm
        env:
        - name: SITE_URL
          value: "https://danger.staging.wetfish.net"
