apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wetfish-staging
resources:
  - ../../base
images:
  - name: WIKI_NGINX_IMAGE
    newName: ghcr.io/cybaxx/web-services-k8s/wiki
    newTag: staging-nginx
  - name: WIKI_PHP_IMAGE
    newName: ghcr.io/cybaxx/web-services-k8s/wiki
    newTag: staging-php
patches:
  - path: ingress-patch.yaml
  - path: env-patch.yaml
