apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glitch-ingress
  annotations:
    cert-manager.io/cluster-issuer: wetfish-selfsigned
spec:
  tls:
  - hosts:
    - glitch.wetfish.local
    secretName: glitch-tls
  rules:
  - host: glitch.wetfish.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: glitch-web
            port:
              number: 80
