apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wetfish-dev
resources:
  - ../../base
images:
  - name: GLITCH_NGINX_IMAGE
    newName: wetfish-registry:5000/glitch
    newTag: nginx
  - name: GLITCH_PHP_IMAGE
    newName: wetfish-registry:5000/glitch
    newTag: php
patches:
  - path: ingress-patch.yaml
