apiVersion: v1
kind: Secret
metadata:
  name: danger-mysql-secret
  namespace: wetfish-dev
  labels:
    app: danger
    component: mysql
type: Opaque
data:
  mysql-root-password: ZGFuZ2VycGFzcw== # dangerpass
  mysql-user: ZGFuZ2VydXNlcg== # dangeruser
  mysql-password: ZGFuZ2VycGFzcw== # dangerpass
  mysql-database: ZGFuZ2VyZGI= # dangerdb
