apiVersion: apps/v1
kind: Deployment
metadata:
  name: danger-web
spec:
  template:
    spec:
      containers:
      - name: php-fpm
        env:
        - name: SITE_URL
          value: "http://danger.wetfish.local"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: danger-mysql-pvc
spec:
  storageClassName: local-path
