apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wetfish-dev
resources:
  - ../../base
images:
  - name: HOME_IMAGE
    newName: wetfish-registry:5000/home
    newTag: latest
patches:
  - path: ingress-patch.yaml
