apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-web
spec:
  template:
    spec:
      containers:
      - name: php-fpm
        env:
        - name: SITE_URL
          value: "https://wiki.wetfish.net"
