apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: prometheus-stack-values
    files:
      - values.yaml=../../../../monitoring/values/prometheus-stack-values.yaml
  - name: loki-values
    files:
      - values.yaml=../../../../monitoring/values/loki-values.yaml
  - name: tempo-values
    files:
      - values.yaml=../../../../monitoring/values/tempo-values.yaml
  - name: promtail-values
    files:
      - values.yaml=../../../../monitoring/values/promtail-values.yaml
