apiVersion: v1
kind: Secret
metadata:
  name: click-mysql-secret
  namespace: wetfish-dev
  labels:
    app: click
    component: mysql
type: Opaque
data:
  mysql-root-password: Y2xpY2twYXNz # clickpass
  mysql-user: Y2xpY2t1c2Vy # clickuser
  mysql-password: Y2xpY2twYXNz # clickpass
  mysql-database: Y2xpY2tkYg== # clickdb
