apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - staging.wetfish.net
  rules:
  - host: staging.wetfish.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home-web
            port:
              number: 80
