apiVersion: v1
kind: Secret
metadata:
  name: wiki-mysql-secret
  namespace: wetfish-dev
  labels:
    app: wiki
    component: mysql
type: Opaque
data:
  mysql-root-password: d2lraXBhc3M= # wikipass
  mysql-user: d2lraXVzZXI= # wikiuser
  mysql-password: d2lraXBhc3M= # wikipass
  mysql-database: d2lraWRi # wikidb
