apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-web
spec:
  template:
    spec:
      containers:
      - name: php-fpm
        env:
        - name: SITE_URL
          value: "https://wiki.wetfish.local"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-mysql-pvc
spec:
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-uploads-pvc
spec:
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-wwwroot-pvc
spec:
  storageClassName: local-path
