apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wiki-ingress
  annotations:
    cert-manager.io/cluster-issuer: wetfish-selfsigned
spec:
  tls:
  - hosts:
    - wiki.wetfish.local
    secretName: wiki-tls
  rules:
  - host: wiki.wetfish.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wiki-web
            port:
              number: 80
