apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wetfish-dev
resources:
  - ../../base
  - secret.yaml
images:
  - name: WIKI_NGINX_IMAGE
    newName: wetfish-registry:5000/wiki
    newTag: nginx
  - name: WIKI_PHP_IMAGE
    newName: wetfish-registry:5000/wiki
    newTag: php
patches:
  - path: ingress-patch.yaml
  - path: env-patch.yaml
