apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: click-ingress
  annotations:
    cert-manager.io/cluster-issuer: wetfish-selfsigned
spec:
  tls:
  - hosts:
    - click.wetfish.local
    secretName: click-tls
  rules:
  - host: click.wetfish.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: click-web
            port:
              number: 80
