apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: danger-ingress
  labels:
    app: danger
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.priority: "100"
spec:
  rules:
  - host: PLACEHOLDER
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: danger-web
            port:
              number: 80
