apiVersion: v1
kind: Secret
metadata:
  name: wiki-secrets
  namespace: wetfish-dev
  labels:
    app: wiki
    component: mediawiki
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bWFyaWFkYgo=
  MYSQL_DATABASE: d2lraWRi
  MYSQL_USER: d2lraXVzZXI=
  MYSQL_PASSWORD: c2VjcmV0
  db-password: c2VjcmV0
  login-password: c2VjcmV0
  admin-password: c2VjcmV0
  ban-password: c2VjcmV0