apiVersion: v1
kind: Secret
metadata:
  name: wiki-secrets
  namespace: wetfish-dev
  labels:
    app: wiki
    component: mediawiki
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: wikipass
  MYSQL_DATABASE: wikidb
  MYSQL_USER: wikiuser
  MYSQL_PASSWORD: wikipass